# Generated by Django 2.1.7 on 2019-04-01 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=320)),
                ('description', models.CharField(max_length=1000)),
                ('weight', models.IntegerField()),
                ('startDate', models.DateField()),
                ('deadline', models.DateField()),
                ('type_a', models.CharField(choices=[('EX', 'Exam'), ('CW', 'Coursework')], default='PR', max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=320)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=320)),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(max_length=1000)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SemesterStudyProfile',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('semester', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=320)),
                ('target', models.IntegerField()),
                ('completed', models.IntegerField(default=0)),
                ('type_act', models.CharField(choices=[('RE', 'Reading'), ('WR', 'Writing'), ('ST', 'Studying'), ('PR', 'Programming')], max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='StudyTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=320)),
                ('description', models.CharField(max_length=1000)),
                ('duration', models.DurationField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Assessment')),
                ('requiredTasks', models.ManyToManyField(related_name='_studytask_requiredTasks_+', to='app.StudyTask')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=320)),
                ('firstname', models.CharField(max_length=24)),
                ('lastname', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=128)),
                ('activeSemester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activeSemester', to='app.SemesterStudyProfile')),
            ],
        ),
        migrations.AddField(
            model_name='studyactivity',
            name='tasks',
            field=models.ManyToManyField(to='app.StudyTask'),
        ),
        migrations.AddField(
            model_name='semesterstudyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AddField(
            model_name='note',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StudyActivity'),
        ),
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StudyTask'),
        ),
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SemesterStudyProfile'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='requiredTasks',
            field=models.ManyToManyField(to='app.StudyTask'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module'),
        ),
    ]
