# Generated by Django 2.1.7 on 2019-03-29 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190322_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersemestertable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='usersemestertable',
            name='user',
        ),
        migrations.AddField(
            model_name='semesterstudyprofile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.DeleteModel(
            name='UserSemesterTable',
        ),
    ]
