# Generated by Django 2.1.7 on 2019-03-29 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190329_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitynotetable',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitynotetable',
            name='note',
        ),
        migrations.RemoveField(
            model_name='assessmentmilestonetable',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentmilestonetable',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='assessmenttasktable',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='assessmenttasktable',
            name='task',
        ),
        migrations.RemoveField(
            model_name='moduleassessmenttable',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='moduleassessmenttable',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semestermoduletable',
            name='module',
        ),
        migrations.RemoveField(
            model_name='semestermoduletable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='tasknotetable',
            name='note',
        ),
        migrations.RemoveField(
            model_name='tasknotetable',
            name='task',
        ),
        migrations.AddField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Module'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assessment'),
        ),
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.SemesterStudyProfile'),
        ),
        migrations.AddField(
            model_name='note',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StudyActivity'),
        ),
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.StudyTask'),
        ),
        migrations.AddField(
            model_name='studytask',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Assessment'),
        ),
        migrations.DeleteModel(
            name='ActivityNoteTable',
        ),
        migrations.DeleteModel(
            name='AssessmentMilestoneTable',
        ),
        migrations.DeleteModel(
            name='AssessmentTaskTable',
        ),
        migrations.DeleteModel(
            name='ModuleAssessmentTable',
        ),
        migrations.DeleteModel(
            name='SemesterModuleTable',
        ),
        migrations.DeleteModel(
            name='TaskNoteTable',
        ),
    ]
