# Generated by Django 2.1.7 on 2019-03-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_assessment_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studytask',
            name='progress',
        ),
    ]
