# Generated by Django 2.1.7 on 2019-03-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_studytask_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskactivitytable',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='taskactivitytable',
            name='task',
        ),
        migrations.AddField(
            model_name='studyactivity',
            name='tasks',
            field=models.ManyToManyField(to='app.StudyTask'),
        ),
        migrations.DeleteModel(
            name='TaskActivityTable',
        ),
    ]
