# Generated by Django 2.1.7 on 2019-03-30 12:00

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190329_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestonerequirestasktable',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='milestonerequirestasktable',
            name='requiredTask',
        ),
        migrations.RemoveField(
            model_name='taskrequirestasktable',
            name='requiredTask',
        ),
        migrations.RemoveField(
            model_name='taskrequirestasktable',
            name='task',
        ),
        migrations.RemoveField(
            model_name='studyactivity',
            name='progress',
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessmentType',
            field=models.CharField(choices=[(app.models.AssessmentType('Exam'), 'Exam'), (app.models.AssessmentType('Coursework'), 'Coursework')], default=app.models.AssessmentType('Coursework'), max_length=11),
        ),
        migrations.AddField(
            model_name='milestone',
            name='requiredTasks',
            field=models.ManyToManyField(to='app.StudyTask'),
        ),
        migrations.AddField(
            model_name='studyactivity',
            name='completed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studytask',
            name='requiredTasks',
            field=models.ManyToManyField(related_name='_studytask_requiredTasks_+', to='app.StudyTask'),
        ),
        migrations.DeleteModel(
            name='MilestoneRequiresTaskTable',
        ),
        migrations.DeleteModel(
            name='TaskRequiresTaskTable',
        ),
    ]
