# Generated by Django 2.1.7 on 2019-03-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190330_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyactivity',
            name='completed',
            field=models.IntegerField(default=0),
        ),
    ]
