# Generated by Django 2.1.7 on 2019-03-30 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190330_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SemesterStudyProfile'),
        ),
    ]
