# Generated by Django 2.1.7 on 2019-03-30 12:35

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190330_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='assessmentType',
            field=models.CharField(choices=[(app.models.AssessmentType('Exam'), 'Exam'), (app.models.AssessmentType('Coursework'), 'Coursework')], max_length=11),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Module'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Assessment'),
        ),
        migrations.AlterField(
            model_name='semesterstudyprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Assessment'),
        ),
    ]
